{{- if .Values.scVerifier.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-sc-verifier-svc
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
  #   service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
  #   service.beta.kubernetes.io/aws-load-balancer-type: external
  labels:
    app: {{ .Release.Name }}-sc-verifier
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.scVerifier.docker.port }}
      targetPort: {{ .Values.scVerifier.docker.targetPort }}
      protocol: TCP
      name: web
    - port: {{ .Values.scVerifier.docker.metricsPort }}
      targetPort: {{ .Values.scVerifier.docker.metricsPort }}
      protocol: TCP
      name: http-metrics
  selector:
    app: {{ .Release.Name }}-sc-verifier
{{- end }}
---
